name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Docker Compose
        run: |
          docker compose up --build

      - name: Test Flask app
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:5000
          if [ $? -ne 200 ]; then
            echo "Test failed"
            exit 1
          fi